# .github/workflows/main.yml

on:
  schedule:
  - cron: '0 12 * * *' # every day at noon

jobs:
  single-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: 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
        GIT_EMAIL: techsquad@antilinuxgang.com # replace me

# .github/workflows/main.yml

on: push

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: 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
        GIT_EMAIL: techsquad@antilinuxgang.com
        MAX_DAYS: 365
        MIN_COMMITS_PER_DAY: 1
        MAX_COMMITS_PER_DAY: 5
